### ISSUE TITLE
Please add README

### ISSUE THREAD

**Issue by songwonderful** [huww98/MyBlog#2]
No **README** found in your REPO, please add this file to help others understand it. Thanks a lot.

**Comment by huww98** [comment]
Hello, I have added a README. Do you want to know anything more? Tell me so that I can perfect my README.

**Comment by songwonderful** [comment]
Thanks for adding README. I want to know more detailed information about the deployment of your blog system. Finally, I suggest you create a release for your project. **Thanks for reply!**
![image](https://user-images.githubusercontent.com/39998050/58714574-95820e00-83f7-11e9-855f-b9501f71bd2b.png)

**Comment by huww98** [comment]
I don't want to add release to this project. This project can not be downloaded then deploy like WordPress. Since this is designed for my personal use, I hard-coded many information that specific to myself.

I will add more detail about how to deploy, though. It should be very easy to build it yourself.

**Comment by huww98** [comment]
Information added. Sorry for the huge delay.
